# generated by datamodel-codegen:
#   filename:  spec.yaml
#   timestamp: 2026-05-06T14:05:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Status(Enum):
    OK = "ok"
    DEGRADED = "degraded"


class Db(Enum):
    CONNECTED = "connected"
    DISCONNECTED = "disconnected"


class HealthGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status
    version: str
    timestamp: AwareDatetime = Field(
        ...,
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )
    db: Db


class V1GetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    api: str
    version: str
    docs: str = Field(..., description="URL to the interactive API documentation")


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str
    message: str


class V1GetResponse1(BaseModel):
    """
    Missing or invalid API key
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    error: Error


class Status1(Enum):
    DRAFT = "draft"
    OPEN = "open"
    CLOSED = "closed"
    UNPUBLISHED = "unpublished"
    CANCELLED = "cancelled"
    POSTPONED = "postponed"
    SCHEDULE = "schedule"


class SortDirection(Enum):
    ASC = "asc"
    DESC = "desc"


class V1EventsGetParametersQuery(BaseModel):
    page: int | None = Field(0, ge=0, le=9007199254740991)
    pageSize: int | None = Field(20, ge=1, le=50)
    status: Status1 | None = None
    search: str | None = None
    startBefore: AwareDatetime | None = Field(
        None,
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )
    startAfter: AwareDatetime | None = Field(
        None,
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )
    sortField: str | None = None
    sortDirection: SortDirection | None = None
    filters: str | None = None
    fields: str | None = None


class Type(Enum):
    TEXT = "text"
    IMAGE = "image"
    VIDEO = "video"


class DescriptionBlock(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type
    content: str
    id: float


class Schedule(Enum):
    SINGLE_DATE = "Single date"
    MULTIPLE_DATES = "Multiple dates"


class Status2(Enum):
    """
    The status of an event.
    - draft: has not been published
    - open: published and ticket sales are open
    - closed: published, ticket sales are closed but the event will proceed as normal
    - unpublished: was previously published, but is no longer visible
    - cancelled: published, ticket sales closed, event is cancelled
    - postponed: published, ticket sales closed, event is postponed
    - schedule: not yet published, scheduled to be published in the future
    """

    DRAFT = "draft"
    OPEN = "open"
    CLOSED = "closed"
    UNPUBLISHED = "unpublished"
    CANCELLED = "cancelled"
    POSTPONED = "postponed"
    SCHEDULE = "schedule"


class MinPriceCents(Enum):
    """
    Minimum ticket/product price in cents. Does not contain fees.
    """

    NONE_TYPE_NONE = None


class MaxPriceCents(Enum):
    """
    Maximum ticket/product price in cents. Does not contain fees.
    """

    NONE_TYPE_NONE = None


class Location(BaseModel):
    """
    Event location with address and coordinates
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    address: str | None = None
    lat: float | None = None
    lng: float | None = None


class Type1(Enum):
    URL = "url"
    TEXT = "text"


class CustomTerms(BaseModel):
    """
    Custom checkout conditions
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    hasCustomTerms: bool | None = None
    type: Type1 | None = None
    url: str | None = None
    content: str | None = None


class Datum(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = None
    name: str | None = None
    type: str | None = Field(None, description="'event', 'booking', 'recurring', or 'multiple'")
    description: str | None = Field(
        None,
        description="Event description as HTML. Only present when descriptionBlocks is empty.",
    )
    descriptionBlocks: list[DescriptionBlock] | None = Field(
        None,
        description="Rich content blocks for the event description. If present and non-empty, clients should render these instead of the description field.\nEach block has a type (text: HTML content, image: URL, video: YouTube URL) and content string.",
    )
    schedule: Schedule | None = None
    start: AwareDatetime | None = Field(
        None,
        description="For single-date events the start time; for multi-date the first time slot.",
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )
    end: AwareDatetime | None = Field(
        None,
        description="For single-date events the end time; for multi-date the last time slot.",
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )
    multiDayStartTimes: list[str] | None = Field(
        None, description="All start times for multi-day events"
    )
    multiDayEndTimes: list[str] | None = Field(
        None, description="All end times for multi-day events"
    )
    status: Status2 | None = Field(
        None,
        description="The status of an event.\n- draft: has not been published\n- open: published and ticket sales are open\n- closed: published, ticket sales are closed but the event will proceed as normal\n- unpublished: was previously published, but is no longer visible\n- cancelled: published, ticket sales closed, event is cancelled\n- postponed: published, ticket sales closed, event is postponed\n- schedule: not yet published, scheduled to be published in the future",
    )
    itemsSold: float | None = Field(None, description="Total tickets and products sold")
    revenueCents: float | None = Field(None, description="Total event revenue, in cents")
    minPriceCents: float | MinPriceCents | None = Field(
        None,
        description="Minimum ticket/product price in cents. Does not contain fees.",
    )
    maxPriceCents: float | MaxPriceCents | None = Field(
        None,
        description="Maximum ticket/product price in cents. Does not contain fees.",
    )
    currency: str | None = Field(None, description="Currency code (e.g. USD, CAD)")
    timeZone: str | None = Field(
        None, description="IANA time zone (may be missing for pre-2024 events)"
    )
    isPublic: bool | None = Field(None, description="True if the event is public")
    isVirtual: bool | None = Field(None, description="True if the event is virtual")
    location: Location | None = Field(
        None, description="Event location with address and coordinates"
    )
    locationPlaceholder: str | None = Field(
        None, description="Placeholder text to link to location"
    )
    virtualEventLink: str | None = Field(None, description="Link for virtual access")
    venueName: str | None = Field(None, description="Name of the associated seating-chart venue")
    image: str | None = Field(None, description="URL of the event's main image")
    images: list[str] | None = Field(None, description="Gallery images")
    tags: list[str] | None = Field(None, description="Tag metadata")
    customTags: list[str] | None = Field(None, description="Custom tag overlays")
    contentBlocks: list[dict[str, Any]] | None = Field(
        None, description="Structured content (FAQs, etc.)"
    )
    language: str | None = Field(None, description="Event language (e.g. 'en', 'fr')")
    isCancelled: bool | None = Field(None, description="Cancellation flag")
    redirectUrl: str | None = Field(None, description="Post-checkout URL")
    customTerms: CustomTerms | None = Field(None, description="Custom checkout conditions")
    createdAt: AwareDatetime | None = Field(
        None,
        description="Creation timestamp",
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )
    updatedAt: AwareDatetime | None = Field(
        None,
        description="Last update timestamp",
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )


class V1EventsGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[Datum]
    hasMore: bool


class Error1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str
    message: str
    details: Any | None = None


class V1EventsGetResponse1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: Error1


class V1EventsGetResponse2(V1EventsGetResponse1):
    pass


class V1EventsIdGetParametersQuery(BaseModel):
    fields: str | None = None


class DescriptionBlock1(DescriptionBlock):
    pass


class CustomTerms1(CustomTerms):
    """
    Custom checkout conditions
    """


class Data(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = None
    name: str | None = None
    type: str | None = Field(None, description="'event', 'booking', 'recurring', or 'multiple'")
    description: str | None = Field(
        None,
        description="Event description as HTML. Only present when descriptionBlocks is empty.",
    )
    descriptionBlocks: list[DescriptionBlock1] | None = Field(
        None,
        description="Rich content blocks for the event description. If present and non-empty, clients should render these instead of the description field.\nEach block has a type (text: HTML content, image: URL, video: YouTube URL) and content string.",
    )
    schedule: Schedule | None = None
    start: AwareDatetime | None = Field(
        None,
        description="For single-date events the start time; for multi-date the first time slot.",
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )
    end: AwareDatetime | None = Field(
        None,
        description="For single-date events the end time; for multi-date the last time slot.",
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )
    multiDayStartTimes: list[str] | None = Field(
        None, description="All start times for multi-day events"
    )
    multiDayEndTimes: list[str] | None = Field(
        None, description="All end times for multi-day events"
    )
    status: Status2 | None = Field(
        None,
        description="The status of an event.\n- draft: has not been published\n- open: published and ticket sales are open\n- closed: published, ticket sales are closed but the event will proceed as normal\n- unpublished: was previously published, but is no longer visible\n- cancelled: published, ticket sales closed, event is cancelled\n- postponed: published, ticket sales closed, event is postponed\n- schedule: not yet published, scheduled to be published in the future",
    )
    itemsSold: float | None = Field(None, description="Total tickets and products sold")
    revenueCents: float | None = Field(None, description="Total event revenue, in cents")
    minPriceCents: float | MinPriceCents | None = Field(
        None,
        description="Minimum ticket/product price in cents. Does not contain fees.",
    )
    maxPriceCents: float | MaxPriceCents | None = Field(
        None,
        description="Maximum ticket/product price in cents. Does not contain fees.",
    )
    currency: str | None = Field(None, description="Currency code (e.g. USD, CAD)")
    timeZone: str | None = Field(
        None, description="IANA time zone (may be missing for pre-2024 events)"
    )
    isPublic: bool | None = Field(None, description="True if the event is public")
    isVirtual: bool | None = Field(None, description="True if the event is virtual")
    location: Location | None = Field(
        None, description="Event location with address and coordinates"
    )
    locationPlaceholder: str | None = Field(
        None, description="Placeholder text to link to location"
    )
    virtualEventLink: str | None = Field(None, description="Link for virtual access")
    venueName: str | None = Field(None, description="Name of the associated seating-chart venue")
    image: str | None = Field(None, description="URL of the event's main image")
    images: list[str] | None = Field(None, description="Gallery images")
    tags: list[str] | None = Field(None, description="Tag metadata")
    customTags: list[str] | None = Field(None, description="Custom tag overlays")
    contentBlocks: list[dict[str, Any]] | None = Field(
        None, description="Structured content (FAQs, etc.)"
    )
    language: str | None = Field(None, description="Event language (e.g. 'en', 'fr')")
    isCancelled: bool | None = Field(None, description="Cancellation flag")
    redirectUrl: str | None = Field(None, description="Post-checkout URL")
    customTerms: CustomTerms1 | None = Field(None, description="Custom checkout conditions")
    createdAt: AwareDatetime | None = Field(
        None,
        description="Creation timestamp",
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )
    updatedAt: AwareDatetime | None = Field(
        None,
        description="Last update timestamp",
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )


class V1EventsIdGetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data


class V1EventsIdGetResponse1(V1EventsGetResponse1):
    pass


class V1EventsIdGetResponse2(V1EventsGetResponse1):
    pass


class V1EventsIdGetResponse3(V1EventsGetResponse1):
    pass


class DescriptionBlock2(BaseModel):
    type: Type
    content: str
    id: float


class Status4(Enum):
    """
    Event status (e.g. draft, open, closed, cancelled)
    """

    DRAFT = "draft"
    OPEN = "open"
    CLOSED = "closed"
    UNPUBLISHED = "unpublished"
    CANCELLED = "cancelled"
    POSTPONED = "postponed"
    SCHEDULE = "schedule"


class Privacy(Enum):
    """
    Public events appear on discover; private are link-only
    """

    PUBLIC = "public"
    PRIVATE = "private"


class EventType(Enum):
    """
    Virtual or in-person
    """

    VIRTUAL = "virtual"
    INPERSON = "inperson"


class CustomTerms2(BaseModel):
    """
    Custom terms and conditions
    """

    hasCustomTerms: bool
    type: Type1
    url: str
    content: str


class V1EventsIdPatchRequest(BaseModel):
    name: str | None = Field(None, description="Event name")
    description: str | None = Field(None, description="Event description (HTML supported)")
    descriptionBlocks: list[DescriptionBlock2] | None = Field(
        None, description="Rich content blocks for the event description"
    )
    status: Status4 | None = Field(
        None, description="Event status (e.g. draft, open, closed, cancelled)"
    )
    start: AwareDatetime | None = Field(
        None,
        description="Start date/time in UTC",
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )
    end: AwareDatetime | None = Field(
        None,
        description="End date/time in UTC",
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )
    hasEndDate: bool | None = Field(None, description="Whether the event has a specified end time")
    privacy: Privacy | None = Field(
        None, description="Public events appear on discover; private are link-only"
    )
    eventType: EventType | None = Field(None, description="Virtual or in-person")
    virtualEventLink: str | None = Field(None, description="Link to virtual event")
    address: str | None = Field(None, description="Event location address")
    locationPlaceholder: str | None = Field(
        None, description="Placeholder text when no address is set"
    )
    timeZone: str | None = Field(None, description='IANA time zone (e.g. "America/New_York")')
    collectEmails: bool | None = Field(
        None, description="Enable checkout; if false customers cannot order"
    )
    redirectUrl: str | None = Field(None, description="URL to redirect to after checkout")
    customTerms: CustomTerms2 | None = Field(None, description="Custom terms and conditions")
    customTags: list[str] | None = Field(None, description="Custom tag overlays")


class DescriptionBlock3(DescriptionBlock):
    pass


class CustomTerms3(CustomTerms):
    """
    Custom checkout conditions
    """


class Data1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = None
    name: str | None = None
    type: str | None = Field(None, description="'event', 'booking', 'recurring', or 'multiple'")
    description: str | None = Field(
        None,
        description="Event description as HTML. Only present when descriptionBlocks is empty.",
    )
    descriptionBlocks: list[DescriptionBlock3] | None = Field(
        None,
        description="Rich content blocks for the event description. If present and non-empty, clients should render these instead of the description field.\nEach block has a type (text: HTML content, image: URL, video: YouTube URL) and content string.",
    )
    schedule: Schedule | None = None
    start: AwareDatetime | None = Field(
        None,
        description="For single-date events the start time; for multi-date the first time slot.",
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )
    end: AwareDatetime | None = Field(
        None,
        description="For single-date events the end time; for multi-date the last time slot.",
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )
    multiDayStartTimes: list[str] | None = Field(
        None, description="All start times for multi-day events"
    )
    multiDayEndTimes: list[str] | None = Field(
        None, description="All end times for multi-day events"
    )
    status: Status2 | None = Field(
        None,
        description="The status of an event.\n- draft: has not been published\n- open: published and ticket sales are open\n- closed: published, ticket sales are closed but the event will proceed as normal\n- unpublished: was previously published, but is no longer visible\n- cancelled: published, ticket sales closed, event is cancelled\n- postponed: published, ticket sales closed, event is postponed\n- schedule: not yet published, scheduled to be published in the future",
    )
    itemsSold: float | None = Field(None, description="Total tickets and products sold")
    revenueCents: float | None = Field(None, description="Total event revenue, in cents")
    minPriceCents: float | MinPriceCents | None = Field(
        None,
        description="Minimum ticket/product price in cents. Does not contain fees.",
    )
    maxPriceCents: float | MaxPriceCents | None = Field(
        None,
        description="Maximum ticket/product price in cents. Does not contain fees.",
    )
    currency: str | None = Field(None, description="Currency code (e.g. USD, CAD)")
    timeZone: str | None = Field(
        None, description="IANA time zone (may be missing for pre-2024 events)"
    )
    isPublic: bool | None = Field(None, description="True if the event is public")
    isVirtual: bool | None = Field(None, description="True if the event is virtual")
    location: Location | None = Field(
        None, description="Event location with address and coordinates"
    )
    locationPlaceholder: str | None = Field(
        None, description="Placeholder text to link to location"
    )
    virtualEventLink: str | None = Field(None, description="Link for virtual access")
    venueName: str | None = Field(None, description="Name of the associated seating-chart venue")
    image: str | None = Field(None, description="URL of the event's main image")
    images: list[str] | None = Field(None, description="Gallery images")
    tags: list[str] | None = Field(None, description="Tag metadata")
    customTags: list[str] | None = Field(None, description="Custom tag overlays")
    contentBlocks: list[dict[str, Any]] | None = Field(
        None, description="Structured content (FAQs, etc.)"
    )
    language: str | None = Field(None, description="Event language (e.g. 'en', 'fr')")
    isCancelled: bool | None = Field(None, description="Cancellation flag")
    redirectUrl: str | None = Field(None, description="Post-checkout URL")
    customTerms: CustomTerms3 | None = Field(None, description="Custom checkout conditions")
    createdAt: AwareDatetime | None = Field(
        None,
        description="Creation timestamp",
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )
    updatedAt: AwareDatetime | None = Field(
        None,
        description="Last update timestamp",
        pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$",
    )


class V1EventsIdPatchResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data1


class V1EventsIdPatchResponse1(V1EventsGetResponse1):
    pass


class V1EventsIdPatchResponse2(V1EventsGetResponse1):
    pass


class V1EventsIdPatchResponse3(V1EventsGetResponse1):
    pass


class V1EventsIdPatchResponse4(V1EventsGetResponse1):
    pass
