export { contactsService, type ContactsService } from './client'
export type {
  AttachPaymentMethodBody,
  AttachPaymentMethodResult,
  BulkUpsertContactsResult,
  Contact,
  ContactActivity,
  ContactActivityListParams,
  ContactActivityType,
  ContactBulkUpsertBody,
  ContactCountResult,
  ContactCreateBody,
  ContactListParams,
  ContactMergeResolution,
  ContactStatus,
  ContactUpdateBody,
  ContactWithOrderDetails,
  DeletedContact,
  ListContactActivityResponse,
  ListContactsResponse,
  PaymentMethod,
  PaymentMethodSetupIntent,
  PaymentMethodStatus,
  RemovedPaymentMethod,
} from './types'
